[package]
name = "maki-benchmark"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "maki-benchmark"
path = "src/main.rs"

[dependencies]
maki-nbdkit.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
