[package]
name = "maki-witness-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "maki-witness"
path = "src/main.rs"

[dependencies]
maki-witness.workspace = true
maki-backing.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
rcgen.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
