[package]
name = "maki-check"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "maki-check"
path = "src/main.rs"

[dependencies]
maki-format.workspace = true
maki-backing.workspace = true

[dev-dependencies]
tempfile.workspace = true
uuid.workspace = true
