[package]
name = "maki-crypto-grpc"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
maki-crypto.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
tonic = "0.12"
prost = "0.13"
zeroize.workspace = true

[dev-dependencies]
maki-backing.workspace = true
maki-core.workspace = true
maki-format.workspace = true
maki-crypto-local.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
